# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Test Nightly
on:
  # Once weekly on Wednesdays at 02:00 UTC.
  schedule:
    - cron: '0 2 * * 3'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        php: ['8.1','8.0','7.4']
      fail-fast: false
    name: WP nightly / PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@2.7.0
      with:
        php-version: ${{ matrix.php }}
        extensions: mysqli, xmlwriter
        coverage: none

    - name: Install dependencies
      run: |
        sudo systemctl start mysql.service
        composer require --dev --update-with-dependencies --prefer-dist roots/wordpress-full="dev-nightly"
        mysqladmin -uroot -proot create wordpress_test

    - name: Run the tests
      run: composer test
